export const socialData = [
  { name: 'GitLab', slug: 'gitlab', category: 'Code' },
  { name: 'Bitbucket', slug: 'bitbucket', category: 'Code' },
  { name: 'LinkedIn', slug: 'linkedin', category: 'Professional' },
  { name: 'X', slug: 'x', category: 'Social' },
  { name: 'Facebook', slug: 'facebook', category: 'Social' },
  { name: 'Instagram', slug: 'instagram', category: 'Social' },
  { name: 'YouTube', slug: 'youtube', category: 'Media' },
  { name: 'TikTok', slug: 'tiktok', category: 'Media' },
  { name: 'Twitch', slug: 'twitch', category: 'Media' },
  { name: 'Discord', slug: 'discord', category: 'Community' },
  { name: 'Slack', slug: 'slack', category: 'Community' },
  { name: 'Reddit', slug: 'reddit', category: 'Community' },
  { name: 'Stack Overflow', slug: 'stackoverflow', category: 'Community' },
  { name: 'Dev.to', slug: 'devdotto', category: 'Writing' },
  { name: 'Medium', slug: 'medium', category: 'Writing' },
  { name: 'Hashnode', slug: 'hashnode', category: 'Writing' },
  { name: 'CodePen', slug: 'codepen', category: 'Showcase' },
  { name: 'Dribbble', slug: 'dribbble', category: 'Design' },
  { name: 'Behance', slug: 'behance', category: 'Design' },
  { name: 'Figma', slug: 'figma', category: 'Design' },
  { name: 'Kaggle', slug: 'kaggle', category: 'Data' },
  { name: 'LeetCode', slug: 'leetcode', category: 'Community' },
  { name: 'HackerRank', slug: 'hackerrank', category: 'Community' },
  { name: 'Product Hunt', slug: 'producthunt', category: 'Community' },
]
