export const socialData = [
  { name: 'GitLab', slug: 'gitlab', category: 'Code' },
  { name: 'Bitbucket', slug: 'bitbucket', category: 'Code' },
  { name: 'LinkedIn', slug: 'linkedin', category: 'Professional' },
  { name: 'Instagram', slug: 'instagram', category: 'Social' },
  { name: 'Discord', slug: 'discord', category: 'Community' },
  { name: 'Stack Overflow', slug: 'stackoverflow', category: 'Community' },
  { name: 'Dev.to', slug: 'devto', category: 'Writing' },
  { name: 'CodePen', slug: 'codepen', category: 'Showcase' },
  { name: 'Gmail', slug: 'gmail', category: 'Contact' },
  { name: 'Twitter / X', slug: 'twitter', category: 'Social' },
  { name: 'Medium', slug: 'md', category: 'Writing' },
  { name: 'Vercel', slug: 'vercel', category: 'Deployment' },
  { name: 'Netlify', slug: 'netlify', category: 'Deployment' },
  { name: 'Heroku', slug: 'heroku', category: 'Deployment' },
  { name: 'GCP', slug: 'gcp', category: 'Cloud' },
  { name: 'Azure', slug: 'azure', category: 'Cloud' },
  { name: 'AWS', slug: 'aws', category: 'Cloud' },
  { name: 'Firebase', slug: 'firebase', category: 'Cloud' },
  { name: 'Supabase', slug: 'supabase', category: 'Cloud' },
  { name: 'Deno', slug: 'deno', category: 'Runtime' },
  { name: 'Bun', slug: 'bun', category: 'Runtime' },
  { name: 'PlanetScale', slug: 'planetscale', category: 'Data' },
]