export const techData = [
  // --- Your Original Techs (Unchanged) ---
  { name: 'React', slug: 'react', category: 'Frontend' },
  { name: 'Next.js', slug: 'nextjs', category: 'Frontend' },
  { name: 'Vue.js', slug: 'vue', category: 'Frontend' },
  { name: 'Nuxt.js', slug: 'nuxtjs', category: 'Frontend' },
  { name: 'Angular', slug: 'angular', category: 'Frontend' },
  { name: 'Svelte', slug: 'svelte', category: 'Frontend' },
  { name: 'Remix', slug: 'remix', category: 'Frontend' },
  { name: 'Solid', slug: 'solidjs', category: 'Frontend' },
  { name: 'Astro', slug: 'astro', category: 'Frontend' },
  { name: 'Tailwind CSS', slug: 'tailwind', category: 'Frontend' },
  { name: 'Bootstrap', slug: 'bootstrap', category: 'Frontend' },
  { name: 'Material UI', slug: 'materialui', category: 'Frontend' },
  { name: 'Redux', slug: 'redux', category: 'Frontend' },
  { name: 'Vite', slug: 'vite', category: 'Tooling' },
  { name: 'Webpack', slug: 'webpack', category: 'Tooling' },
  { name: 'Rollup', slug: 'rollupjs', category: 'Tooling' },
  { name: 'Babel', slug: 'babel', category: 'Tooling' },
  { name: 'Jenkins', slug: 'jenkins', category: 'DevOps' },
  { name: 'Jest', slug: 'jest', category: 'Testing' },
  { name: 'Vitest', slug: 'vitest', category: 'Testing' },
  { name: 'Cypress', slug: 'cypress', category: 'Testing' },
  { name: 'npm', slug: 'npm', category: 'Tooling' },
  { name: 'Yarn', slug: 'yarn', category: 'Tooling' },
  { name: 'pnpm', slug: 'pnpm', category: 'Tooling' },
  { name: 'Node.js', slug: 'nodejs', category: 'Backend' },
  { name: 'Express', slug: 'express', category: 'Backend' },
  { name: 'NestJS', slug: 'nestjs', category: 'Backend' },
  { name: 'Django', slug: 'django', category: 'Backend' },
  { name: 'Flask', slug: 'flask', category: 'Backend' },
  { name: 'FastAPI', slug: 'fastapi', category: 'Backend' },
  { name: 'Laravel', slug: 'laravel', category: 'Backend' },
  { name: 'Ruby on Rails', slug: 'rails', category: 'Backend' },
  { name: 'Spring', slug: 'spring', category: 'Backend' },
  { name: 'GraphQL', slug: 'graphql', category: 'Backend' },
  { name: 'Apollo GraphQL', slug: 'apollo', category: 'Backend' },
  { name: 'Prisma', slug: 'prisma', category: 'Data' },
  { name: 'PostgreSQL', slug: 'postgres', category: 'Data' },
  { name: 'MySQL', slug: 'mysql', category: 'Data' },
  { name: 'MongoDB', slug: 'mongodb', category: 'Data' },
  { name: 'Redis', slug: 'redis', category: 'Data' },
  { name: 'SQLite', slug: 'sqlite', category: 'Data' },
  { name: 'Firebase', slug: 'firebase', category: 'Data' },
  { name: 'Supabase', slug: 'supabase', category: 'Data' },
  { name: 'Elasticsearch', slug: 'elasticsearch', category: 'Data' },
  { name: 'Docker', slug: 'docker', category: 'DevOps' },
  { name: 'Kubernetes', slug: 'kubernetes', category: 'DevOps' },
  { name: 'AWS Lambda', slug: 'aws', category: 'Cloud' },
  { name: 'Vercel', slug: 'vercel', category: 'Cloud' },
  { name: 'Netlify', slug: 'netlify', category: 'Cloud' },
  { name: 'Heroku', slug: 'heroku', category: 'Cloud' },
  { name: 'Cloudflare', slug: 'cloudflare', category: 'Cloud' },
  { name: 'Terraform', slug: 'terraform', category: 'DevOps' },
  { name: 'Ansible', slug: 'ansible', category: 'DevOps' },
  { name: 'GitHub Actions', slug: 'githubactions', category: 'DevOps' },
  { name: 'GitHub', slug: 'github', category: 'DevOps' },
  { name: 'GitLab', slug: 'gitlab', category: 'DevOps' },
  { name: 'Bitbucket', slug: 'bitbucket', category: 'DevOps' },
  { name: 'Linux', slug: 'linux', category: 'Platform' },
  { name: 'Ubuntu', slug: 'ubuntu', category: 'Platform' },
  { name: 'Nginx', slug: 'nginx', category: 'DevOps' },
  { name: 'Postman', slug: 'postman', category: 'Tooling' },
  { name: 'Figma', slug: 'figma', category: 'Design' },
  { name: 'Notion', slug: 'notion', category: 'Collaboration' },
  { name: 'Neovim', slug: 'neovim', category: 'Tooling' },
  { name: 'IntelliJ IDEA', slug: 'idea', category: 'Tooling' },
  { name: 'Flutter', slug: 'flutter', category: 'Mobile' },
  { name: 'Kotlin', slug: 'kotlin', category: 'Language' },
  { name: 'Swift', slug: 'swift', category: 'Language' },
  { name: 'Dart', slug: 'dart', category: 'Language' },
  { name: 'JavaScript', slug: 'js', category: 'Language' },
  { name: 'TypeScript', slug: 'ts', category: 'Language' },
  { name: 'Python', slug: 'py', category: 'Language' },
  { name: 'Go', slug: 'go', category: 'Language' },
  { name: 'Rust', slug: 'rust', category: 'Language' },
  { name: 'C++', slug: 'cpp', category: 'Language' },
  { name: '.NET', slug: 'dotnet', category: 'Language' },
  { name: 'PHP', slug: 'php', category: 'Language' },
  { name: 'Ruby', slug: 'ruby', category: 'Language' },
  { name: 'Bash', slug: 'bash', category: 'Language' },
  { name: 'Gatsby', slug: 'gatsby', category: 'Frontend' },
  { name: 'HTML5', slug: 'html', category: 'Frontend' },
  { name: 'CSS3', slug: 'css', category: 'Frontend' },
  { name: 'Sass', slug: 'sass', category: 'Frontend' },
  { name: 'Less', slug: 'less', category: 'Frontend' },
  { name: 'Styled Components', slug: 'styledcomponents', category: 'Frontend' },
  { name: 'Htmx', slug: 'htmx', category: 'Frontend' },
  { name: 'Ember', slug: 'ember', category: 'Frontend' },
  { name: 'Bun', slug: 'bun', category: 'Tooling' },
  { name: 'Deno', slug: 'deno', category: 'Tooling' },
  { name: 'Gulp', slug: 'gulp', category: 'Tooling' },
  { name: 'VS Code', slug: 'vscode', category: 'Tooling' },
  { name: 'Vim', slug: 'vim', category: 'Tooling' },
  { name: 'AdonisJS', slug: 'adonis', category: 'Backend' },
  { name: 'Haskell', slug: 'haskell', category: 'Language' },
  { name: 'Java', slug: 'java', category: 'Language' },
  { name: 'Lua', slug: 'lua', category: 'Language' },
  { name: 'Matlab', slug: 'matlab', category: 'Language' },
  { name: 'R', slug: 'r', category: 'Language' },
  { name: 'Scala', slug: 'scala', category: 'Language' },
  { name: 'Zig', slug: 'zig', category: 'Language' },
  { name: 'Solidity', slug: 'solidity', category: 'Language' },
  { name: 'Cassandra', slug: 'cassandra', category: 'Data' },
  { name: 'Azure', slug: 'azure', category: 'Cloud' },
  { name: 'Google Cloud', slug: 'gcp', category: 'Cloud' },
  { name: 'Prometheus', slug: 'prometheus', category: 'DevOps' },
  { name: 'Grafana', slug: 'grafana', category: 'DevOps' },
  { name: 'Unity', slug: 'unity', category: 'GameDev' },
  { name: 'Unreal Engine', slug: 'unreal', category: 'GameDev' },
  { name: 'Godot', slug: 'godot', category: 'GameDev' },
  { name: 'Android Studio', slug: 'androidstudio', category: 'Mobile' },
  { name: 'Tauri', slug: 'tauri', category: 'Mobile' },
  { name: 'Photoshop', slug: 'ps', category: 'Design' },
  { name: 'Illustrator', slug: 'ai', category: 'Design' },
  { name: 'After Effects', slug: 'ae', category: 'Design' },
  { name: 'Blender', slug: 'blender', category: 'Design' },
]