export const techData = [
  { name: 'React', slug: 'react', category: 'Frontend' },
  { name: 'Next.js', slug: 'nextdotjs', category: 'Frontend' },
  { name: 'Vue.js', slug: 'vuedotjs', category: 'Frontend' },
  { name: 'Nuxt.js', slug: 'nuxtdotjs', category: 'Frontend' },
  { name: 'Angular', slug: 'angular', category: 'Frontend' },
  { name: 'Svelte', slug: 'svelte', category: 'Frontend' },
  { name: 'Remix', slug: 'remix', category: 'Frontend' },
  { name: 'Solid', slug: 'solid', category: 'Frontend' },
  { name: 'Astro', slug: 'astro', category: 'Frontend' },
  { name: 'Tailwind CSS', slug: 'tailwindcss', category: 'Frontend' },
  { name: 'Bootstrap', slug: 'bootstrap', category: 'Frontend' },
  { name: 'Material UI', slug: 'mui', category: 'Frontend' },
  { name: 'Chakra UI', slug: 'chakraui', category: 'Frontend' },
  { name: 'Ant Design', slug: 'antdesign', category: 'Frontend' },
  { name: 'Redux', slug: 'redux', category: 'Frontend' },
  { name: 'Vite', slug: 'vite', category: 'Tooling' },
  { name: 'Webpack', slug: 'webpack', category: 'Tooling' },
  { name: 'Rollup', slug: 'rollupdotjs', category: 'Tooling' },
  { name: 'Babel', slug: 'babel', category: 'Tooling' },
  { name: 'ESLint', slug: 'eslint', category: 'Tooling' },
  { name: 'Prettier', slug: 'prettier', category: 'Tooling' },
  { name: 'Jest', slug: 'jest', category: 'Testing' },
  { name: 'Vitest', slug: 'vitest', category: 'Testing' },
  { name: 'Cypress', slug: 'cypress', category: 'Testing' },
  { name: 'Testing Library', slug: 'testinglibrary', category: 'Testing' },
  { name: 'Storybook', slug: 'storybook', category: 'Tooling' },
  { name: 'npm', slug: 'npm', category: 'Tooling' },
  { name: 'Yarn', slug: 'yarn', category: 'Tooling' },
  { name: 'pnpm', slug: 'pnpm', category: 'Tooling' },
  { name: 'Node.js', slug: 'nodedotjs', category: 'Backend' },
  { name: 'Express', slug: 'express', category: 'Backend' },
  { name: 'NestJS', slug: 'nestjs', category: 'Backend' },
  { name: 'Fastify', slug: 'fastify', category: 'Backend' },
  { name: 'Django', slug: 'django', category: 'Backend' },
  { name: 'Flask', slug: 'flask', category: 'Backend' },
  { name: 'FastAPI', slug: 'fastapi', category: 'Backend' },
  { name: 'Laravel', slug: 'laravel', category: 'Backend' },
  { name: 'Ruby on Rails', slug: 'rubyonrails', category: 'Backend' },
  { name: 'Spring', slug: 'spring', category: 'Backend' },
  { name: 'GraphQL', slug: 'graphql', category: 'Backend' },
  { name: 'Apollo GraphQL', slug: 'apollographql', category: 'Backend' },
  { name: 'Prisma', slug: 'prisma', category: 'Data' },
  { name: 'PostgreSQL', slug: 'postgresql', category: 'Data' },
  { name: 'MySQL', slug: 'mysql', category: 'Data' },
  { name: 'MongoDB', slug: 'mongodb', category: 'Data' },
  { name: 'Redis', slug: 'redis', category: 'Data' },
  { name: 'SQLite', slug: 'sqlite', category: 'Data' },
  { name: 'MariaDB', slug: 'mariadb', category: 'Data' },
  { name: 'Firebase', slug: 'firebase', category: 'Data' },
  { name: 'Supabase', slug: 'supabase', category: 'Data' },
  { name: 'Elasticsearch', slug: 'elasticsearch', category: 'Data' },
  { name: 'Neo4j', slug: 'neo4j', category: 'Data' },
  { name: 'Docker', slug: 'docker', category: 'DevOps' },
  { name: 'Kubernetes', slug: 'kubernetes', category: 'DevOps' },
  { name: 'AWS Lambda', slug: 'awslambda', category: 'Cloud' },
  { name: 'Google Cloud', slug: 'googlecloud', category: 'Cloud' },
  { name: 'Railway', slug: 'railway', category: 'Cloud' },
  { name: 'Vercel', slug: 'vercel', category: 'Cloud' },
  { name: 'Netlify', slug: 'netlify', category: 'Cloud' },
  { name: 'Heroku', slug: 'heroku', category: 'Cloud' },
  { name: 'DigitalOcean', slug: 'digitalocean', category: 'Cloud' },
  { name: 'Cloudflare', slug: 'cloudflare', category: 'Cloud' },
  { name: 'Terraform', slug: 'terraform', category: 'DevOps' },
  { name: 'Ansible', slug: 'ansible', category: 'DevOps' },
  { name: 'Jenkins', slug: 'jenkins', category: 'DevOps' },
  { name: 'GitHub Actions', slug: 'githubactions', category: 'DevOps' },
  { name: 'GitHub', slug: 'github', category: 'DevOps' },
  { name: 'GitLab', slug: 'gitlab', category: 'DevOps' },
  { name: 'Bitbucket', slug: 'bitbucket', category: 'DevOps' },
  { name: 'Linux', slug: 'linux', category: 'Platform' },
  { name: 'Ubuntu', slug: 'ubuntu', category: 'Platform' },
  { name: 'Nginx', slug: 'nginx', category: 'DevOps' },
  { name: 'Apache', slug: 'apache', category: 'DevOps' },
  { name: 'Postman', slug: 'postman', category: 'Tooling' },
  { name: 'Figma', slug: 'figma', category: 'Design' },
  { name: 'Slack', slug: 'slack', category: 'Collaboration' },
  { name: 'Notion', slug: 'notion', category: 'Collaboration' },
  { name: 'Jira', slug: 'jira', category: 'Collaboration' },
  { name: 'Trello', slug: 'trello', category: 'Collaboration' },
  { name: 'Confluence', slug: 'confluence', category: 'Collaboration' },
  { name: 'Neovim', slug: 'neovim', category: 'Tooling' },
  { name: 'IntelliJ IDEA', slug: 'intellijidea', category: 'Tooling' },
  { name: 'Android', slug: 'android', category: 'Mobile' },
  { name: 'Ionic', slug: 'ionic', category: 'Mobile' },
  { name: 'Flutter', slug: 'flutter', category: 'Mobile' },
  { name: 'Expo', slug: 'expo', category: 'Mobile' },
  { name: 'Kotlin', slug: 'kotlin', category: 'Language' },
  { name: 'Swift', slug: 'swift', category: 'Language' },
  { name: 'Dart', slug: 'dart', category: 'Language' },
  { name: 'JavaScript', slug: 'javascript', category: 'Language' },
  { name: 'TypeScript', slug: 'typescript', category: 'Language' },
  { name: 'Python', slug: 'python', category: 'Language' },
  { name: 'Go', slug: 'go', category: 'Language' },
  { name: 'Rust', slug: 'rust', category: 'Language' },
  { name: 'C++', slug: 'cplusplus', category: 'Language' },
  { name: '.NET', slug: 'dotnet', category: 'Language' },
  { name: 'PHP', slug: 'php', category: 'Language' },
  { name: 'Ruby', slug: 'ruby', category: 'Language' },
  { name: 'Bash', slug: 'gnubash', category: 'Language' },
  { name: 'OpenJDK', slug: 'openjdk', category: 'Language' },
]
